language: python
python:
 - "2.7"
install:
 - pip install -r requirements.txt
script:
- flake8 scripts --ignore=E128,E501
- coverage run  --source=scripts --omit='*__init__.py' tests/test_runner.py $@
after_success: coveralls